#!/bin/bash -x

while IFS= read -r line; do
    if [[ $line =~ (next-20[0-9]{6})/ ]]; then
        latest="${BASH_REMATCH[1]}"
	break
    fi
done < <(curl -s https://archive.chirpmyradio.com/chirp_next/)

if [ -z "${latest}" ]; then
    echo "::error::Could not find latest CHIRP build" >&2
    exit 1
fi

new_version="${latest#next-}"

# Get the checksum and uri from SHA1SUM file
while IFS= read -r line; do
    if [[ $line =~ ^.*\.app\.zip$ ]]; then
	parts=(${BASH_REMATCH[0]})
	new_sha="${parts[0]}"
	uri="${parts[1]}"
	break
    fi
done < <(curl -s "https://archive.chirpmyradio.com/chirp_next/${latest}/SHA1SUM")

if [ -z "${uri}" ]; then
    echo "::error::Could not find .app.zip file in SHA1SUM" >&2
    exit 1
fi

echo "${version} ${new_sha} ${uri}"

current_version=$(sed -n 's/^[[:space:]]*version[[:space:]]*"\([^"]*\)".*/\1/p' Casks/chirp.rb)
current_sha=$(sed -n 's/^[[:space:]]*sha256[[:space:]]*"\([^"]*\)".*/\1/p' Casks/chirp.rb)

if [ "${current_version}" = "${new_version}" ] && [ "${current_sha}" = "${new_sha}" ]; then
    echo "No update needed"
else
    sed -I "" -e "s/version \"[^\"]*\"/version \"${new_version}\"/" Casks/chirp.rb
    sed -I "" -e "s/sha256 \"[^\"]*\"/sha256 \"${new_sha}\"/" Casks/chirp.rb
    git add Cask/chirp.rb
    git commit -m"Update Chirp to ${new_version}"
    git push
fi
